services:
  Nginx:
    # build: ./nginx
    image: nginx:stable
    container_name: letChat-nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - nginx_networks
    command: ["nginx", "-g", "daemon off;"]

  backend:
    build: ./
    image: backend-image
    container_name: backend-container
    ports:
      - "7000:7000"
    networks:
      - nginx_networks
    env_file:
      - ./.env

networks:
  nginx_networks:
    driver: bridge
