name: Deploy to AWS EC2 INSTANCE

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20"

      - name: copy package.json
        run: cp package.json dist/

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: "npm run build"

      - name: Copy node_modules to build folder
        run: cp -r node_modules dist/

      - name: log build file
        run: ls dist/

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist/

      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" >> dist/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> dist/.env
          echo "SECRET=${{ secrets.SECRET }}" >> dist/.env 
          echo "ALLOWED_ORIGIN=${{ secrets.ALLOWED_ORIGIN }}" >> dist/.env

      - name: change permission on .env content
        run: chmod 777 dist/.env

      - name: Verify artifact content
        run: ls -la ./dist/

      - name: Create Target Directory on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /var/www/myApps
            sudo chown $USER:$USER /var/www/myApps

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          target: /var/www/myApps
          source: ./dist/*
          debug: true

      - name: Install Node.js and Restart App
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /var/www/myApps
            # Set DEBIAN_FRONTEND to noninteractive for the script
            export DEBIAN_FRONTEND=noninteractive

            # Install Node.js if not already installed
            if ! command -v node &> /dev/null; then
            echo "Node.js not found, installing..."
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs
            fi
            # Ensure PM2 is available
            if ! command -v pm2 &> /dev/null; then
            echo "PM2 not found, installing.."
            sudo npm install -g pm2
            fi
            # Restart or start the app
            pm2 restart all || pm2 start ./dist/index.js
