name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20"

      - name: copy package.json
        run: cp package.json dist/

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: "npm run build"
